[package]
name = "altr-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
altr = "0.3.5"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib"]
